# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 403)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 366))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.input = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.input.setObjectName("input")
        self.verticalLayout.addWidget(self.input)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.N_views = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.N_views.setMinimum(1)
        self.N_views.setObjectName("N_views")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.N_views)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.N_proj = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.N_proj.setMaximum(10000)
        self.N_proj.setObjectName("N_proj")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.N_proj)
        self.N_flats = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.N_flats.setObjectName("N_flats")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.N_flats)
        self.N_darks = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.N_darks.setObjectName("N_darks")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.N_darks)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.N_images = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.N_images.setMinimum(1)
        self.N_images.setMaximum(50)
        self.N_images.setProperty("value", 1)
        self.N_images.setObjectName("N_images")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.N_images)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.N_interval = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.N_interval.setMinimum(-1)
        self.N_interval.setMaximum(10000)
        self.N_interval.setProperty("value", -1)
        self.N_interval.setObjectName("N_interval")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.N_interval)
        self.verticalLayout.addLayout(self.formLayout)
        self.leading = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.leading.setObjectName("leading")
        self.verticalLayout.addWidget(self.leading)
        self.before = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.before.setObjectName("before")
        self.verticalLayout.addWidget(self.before)
        self.after = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.after.setObjectName("after")
        self.verticalLayout.addWidget(self.after)
        self.trailing = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.trailing.setObjectName("trailing")
        self.verticalLayout.addWidget(self.trailing)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Reorder Sequence Files"))
        self.input.setText(_translate("Dialog", "Input Folder"))
        self.label.setText(_translate("Dialog", "Number of Views"))
        self.label_2.setText(_translate("Dialog", "Number of Projections"))
        self.label_3.setText(_translate("Dialog", "Number of Flats"))
        self.label_4.setText(_translate("Dialog", "Number of Darks"))
        self.label_5.setText(_translate("Dialog", "Images per angle"))
        self.label_6.setText(_translate("Dialog", "Options: "))
        self.label_7.setText(_translate("Dialog", "Interval for Flats/Darks"))
        self.leading.setText(_translate("Dialog", "Leading Flats/Darks"))
        self.before.setText(_translate("Dialog", "Flats/Darks Before"))
        self.after.setText(_translate("Dialog", "Flats/Darks After"))
        self.trailing.setText(_translate("Dialog", "Trailing Flats"))

